# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure cache directories exist
  file:
    path: "{{ libvirt_image_cache_path }}"
    state: directory

- name: "Create volume"
  environment:
    LIBVIRT_DEFAULT_URI: qemu:///system
  command: >-
    virsh vol-create-as \
    --pool "{{ libvirt_volume.pool }}" \
    --name "{{ libvirt_volume.name }}" \
    --capacity "{{ libvirt_volume.size }}" \
    --format "{{ libvirt_volume.format | default('qcow2') }}"
  register: libvirt_create_volume
  failed_when:
    - "libvirt_create_volume.rc != 0"
    - "'exists already' in libvirt_create_volume.stderr"
    - "'exists already' in libvirt_create_volume.stdout"
  changed_when:
    - "libvirt_create_volume.rc != 1"
    - "'exists already' not in libvirt_create_volume.stderr"
    - "'exists already' not in libvirt_create_volume.stdout"
