- acl:
    default: true
    path: "{{ floorplan.default_image_pool }}"
    entry: "u:libvirt-qemu:r-x"
    state: present

- name: "Delete storage pools"
  block:
    # Stop a storage pool
    - virt_pool:
        command: destroy
        name: "{{ item }}"
      with_items:
        - default
      ignore_errors: true
# Delete a storage pool (destroys contents)
    - virt_pool:
        command: delete
        name: "{{ item }}"
      with_items:
        - default
      ignore_errors: true
    - virt_pool:
        command: undefine
        name: "{{ item }}"
      with_items:
        - default
      ignore_errors: true

- name: "Define, Build, and Start default storage pool"
  block:
    - virt_pool:
        command: define
        name: "{{ item }}"
        xml: '{{ lookup("template", "{{ item }}.xml.j2") }}'
      with_items:
        - default

    - virt_pool:
        command: build
        name: "{{ item }}"
      with_items:
        - default
  
    - virt_pool:
        command: create
        name: "{{ item }}"
      with_items:
        - default
    - virt_pool:
        command: list_pools

- name: "Define network, activate, start network pools"
  block:
    - virt_net:
        command: define
        xml: '{{ lookup("template", "{{ item }}.xml.j2") }}'
        name: "{{ item }}"
      with_items:
        - "air_prov"
        - "air_nat"

    - virt_net:
        state: active
        name: "{{ item }}"
      with_items:
        - "air_prov"
        - "air_nat"

    - virt_net:
        name: "{{ item }}"
        autostart: true
      with_items:
        - "air_prov"
        - "air_nat"

- name: "Create nodes"
  include_tasks: create-vms.yaml
  with_items: 
    - "{{ nodes }}"
  loop_control:
    loop_var: vm_instance