apiVersion: v1
kind: Pod
metadata:
  name: vairship
  namespace: airshipdev
spec:
  hostNetwork: true
  containers:
  - name: libvirt
    image: slfletch/libvirt:0.1.0
    securityContext:
      privileged: true
    command: ["libvirtd"]
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: var-lib-libvirt-images
      mountPath: /var/lib/libvirt/images
    - name: var-run-libvirt
      mountPath: /var/run/libvirt
  - name: virsh
    image: slfletch/virsh:0.1.0
    securityContext:
      privileged: true
    command:
    - bash
    - -cex
    - |
      /var/tmp/entrypoint.sh create_nodes
      tail -f /dev/null 
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: tmp
      mountPath: /tmp
    - name: var-lib-libvirt-images
      mountPath: /var/lib/libvirt/images
    - name: var-run-libvirt
      mountPath: /var/run/libvirt
  - name: sushy-emulator
    image: slfletch/sushy-emulator:0.1.0
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: tmp
      mountPath: /tmp
    - name: var-lib-libvirt-images
      mountPath: /var/lib/libvirt/images
    - name: var-run-libvirt
      mountPath: /var/run/libvirt
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: tmp
    hostPath:
      path: /tmp
  - name: var-lib-libvirt-images
    hostPath:
      path: /tmp/vms
  - name: var-run-libvirt
    hostPath:
      path: /tmp/stuff
