apiVersion: v1
kind: Pod
metadata:
  name: vairship
spec:
  hostNetwork: false 
  containers:
  - name: libvirt
    image: port/libvirt:latest
    tty: true
    securityContext:
      privileged: true
      #SYS_ADMIN required for systemd, need to work out reqs for libvirt
    command:
    - /bin/systemd
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: tmp
      mountPath: /tmp
    - name: run
      mountPath: /run
    - name: var-lib-libvirt-images
      mountPath: /var/lib/libvirt/images
    - name: var-run-libvirt
      mountPath: /var/run/libvirt
    - name: sys-fs-cgroup
      mountPath: /sys/fs/cgroup
      readOnly: false
  - name: virsh
    image: port/virsh:latest
    securityContext:
      privileged: true
    command:
    - bash
    - -cex
    - |
      /opt/ansible/entrypoint.sh create
      tail -f /dev/null 
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: tmp
      mountPath: /tmp
    - name: run
      mountPath: /run
    - name: var-lib-libvirt-images
      mountPath: /var/lib/libvirt/images
    - name: var-run-libvirt
      mountPath: /var/run/libvirt
  - name: sushy
    image: port/sushy:latest
    securityContext:
      privileged: true
    command:
      - bash
      - -cex
      - |
        /entrypoint.sh
        tail -f /dev/null 
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: tmp
      mountPath: /tmp
    - name: run
      mountPath: /run
    - name: var-lib-libvirt-images
      mountPath: /var/lib/libvirt/images
    - name: var-run-libvirt
      mountPath: /var/run/libvirt
  # - name: airshipctl 
  #   image: slfletch/airshipctl:0.1.0
  #   securityContext:
  #     privileged: true
  #   command:
  #     - bash
  #     - -cex
  #     - |
  #       /opt/bin/entrypoint.sh
  #       tail -f /dev/null 
  #   volumeMounts:
  #   - name: dev
  #     mountPath: /dev
  #   - name: tmp
  #     mountPath: /tmp
  #   - name: run
  #     mountPath: /run
  #   - name: var-lib-libvirt-images
  #     mountPath: /var/lib/libvirt/images
  #   - name: var-run-libvirt
  #     mountPath: /var/run/libvirt
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: tmp
    emptyDir:
      medium: "Memory"
  - name: run
    emptyDir:
      medium: "Memory"
  - name: var-lib-libvirt-images
    emptyDir: {}
  - name: var-run-libvirt
    emptyDir: {}
  - name: sys-fs-cgroup
    hostPath:
      path: /sys/fs/cgroup

