- name: Create a directory if it does not exist
  file:
    path: /opt/airshipctl/manifests/site/test-site/shared/baremetalhost/node0{{ a_node }}
    state: directory
    mode: '0755'

- name: "Create boot MacAddress"
  shell: echo $(echo "{{ vm_instance.name }}-{{ a_node }}"|md5sum|sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/')
  register: macAddress

- name: Create bootstraphost
  template:
    src: bootstraphost.yaml.j2
    dest: "/opt/airshipctl/manifests/site/test-site/shared/baremetalhost/node0{{ a_node }}/baremetalhost.yaml"
  with_items: vm_instance
- name: Output file
  shell: "cat /opt/airshipctl/manifests/site/test-site/shared/baremetalhost/node0{{ a_node }}/baremetalhost.yaml"

- name: Create node kustomization
  template:
    src: kustomization.yaml.j2
    dest: "/opt/airshipctl/manifests/site/test-site/shared/baremetalhost/node0{{ a_node }}/kustomization.yaml"
  with_items: vm_instance
- name: Output file
  shell: "cat /opt/airshipctl/manifests/site/test-site/shared/baremetalhost/node0{{ a_node }}/kustomization.yaml"